name: AvolkTestApp
description: project special for Mobyte

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  assets:
    - lib\resources\images\icons8_facebook_64.png
    - lib\resources\images\icons8_vk_64.png
    - lib\resources\images\icons8_ok_64.png
    - lib\resources\images\1.jpg
    - lib\resources\images\2.jpg
    - lib\resources\images\3.jpg
    - lib\resources\images\4.jpg
  fonts:
    - family: museocyrl_100
      fonts:
        - asset: lib\resources\fonts\museocyrl_100.otf
          style: normal
  uses-material-design: true
